# Generated by Django 5.2.5 on 2026-04-26 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usersociallink_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('platform_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='account.userprofile')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['usersociallink_id'], name='account_use_usersoc_fbdd6c_idx')],
            },
        ),
    ]
