# Generated by Django 5.2.5 on 2026-05-03 17:52

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBasicInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profilebasicinfo_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('public_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='portfoliohub.profilesnapshot')),
            ],
        ),
    ]
