# Generated by Django 5.2.5 on 2026-05-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0002_profilebasicinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSocialLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profilesociallink_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('platform_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='portfoliohub.profilesnapshot')),
            ],
        ),
    ]
