# Generated by Django 5.2.5 on 2026-05-03 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0003_profilesociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEducation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profileeducation_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('degree_name', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='portfoliohub.profilesnapshot')),
            ],
        ),
    ]
