# Generated by Django 5.2.5 on 2026-05-09 12:22

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0006_skillcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSkill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('masterskill_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('public_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_skills', to='portfoliohub.skillcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profileskill_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('level', models.IntegerField(default=3)),
                ('years_of_experience', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('is_featured', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='portfoliohub.profilesnapshot')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='portfoliohub.masterskill')),
            ],
            options={
                'unique_together': {('profile_snapshot', 'skill')},
            },
        ),
    ]
