# Generated by Django 5.2.5 on 2026-05-09 13:09

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0007_masterskill_profileskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileProject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profileproject_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField(blank=True, null=True)),
                ('code_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfoliohub.profilesnapshot')),
            ],
        ),
    ]
