# Generated by Django 5.2.5 on 2026-05-09 14:25

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0010_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCertificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profilecertificate_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='portfoliohub.profilesnapshot')),
            ],
        ),
    ]
