# Generated by Django 5.2.5 on 2026-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0012_profileachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLanguage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('masterlanguage_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
    ]
