# Generated by Django 5.2.5 on 2026-05-09 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0013_masterlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLanguage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profilelanguage_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('proficiency', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('professional', 'Professional'), ('native', 'Native')], max_length=30)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_languages', to='portfoliohub.masterlanguage')),
                ('profile_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='portfoliohub.profilesnapshot')),
            ],
            options={
                'ordering': ['position', 'language__name'],
                'unique_together': {('profile_snapshot', 'language')},
            },
        ),
    ]
