# Generated by Django 5.2.5 on 2026-05-10 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0014_profilelanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileHobby',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profilehobby_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('hobby_name', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='portfoliohub.profilesnapshot')),
            ],
            options={
                'ordering': ['position', 'hobby_name'],
            },
        ),
    ]
