# Generated by Django 5.2.5 on 2026-05-10 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0016_profilestrength'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCustomSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profilecustomsection_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sections', to='portfoliohub.profilesnapshot')),
            ],
        ),
    ]
