# Generated by Django 5.2.5 on 2026-05-10 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0017_profilecustomsection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resume_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('template_key', models.CharField(default='modern_ats', max_length=100)),
                ('font_family', models.CharField(default='Poppins', max_length=100)),
                ('primary_color', models.CharField(default='#2563EB', max_length=20)),
                ('layout', models.CharField(default='single_column', max_length=100)),
                ('is_public', models.BooleanField(default=False)),
                ('is_pdf_generated', models.BooleanField(default=False)),
                ('last_generated_pdf', models.FileField(blank=True, null=True, upload_to='resume_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_projects', to='portfoliohub.profilesnapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
