# Generated by Django 5.2.5 on 2026-05-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0019_portfolioproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTheme',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('theme_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='portfolio_themes/previews/')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('template_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='resume_templates/previews/')),
                ('is_ats_friendly', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
