# Generated by Django 5.2.5 on 2026-05-10 11:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0020_portfoliotheme_resumetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotheme',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliotheme',
            name='preview_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='preview_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
