# Generated by Django 5.2.5 on 2026-05-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0021_portfoliotheme_public_id_resumetemplate_public_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='portfoliohub.portfolioproject')),
            ],
        ),
    ]
