# Generated by Django 5.2.5 on 2026-05-10 12:03

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0022_portfolioview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeExport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exported_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('export_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT')], default='pdf', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='portfoliohub.resumeproject')),
            ],
        ),
    ]
