# Generated by Django 5.2.5 on 2026-05-10 12:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0023_resumeexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeproject',
            name='pdf_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resumeproject',
            name='last_generated_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
