# Generated by Django 5.2.5 on 2026-06-11 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0024_resumeproject_pdf_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeproject',
            name='last_generated_pdf',
        ),
        migrations.RemoveField(
            model_name='resumeproject',
            name='template_key',
        ),
        migrations.AddField(
            model_name='resumeproject',
            name='resume_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resume_projects', to='portfoliohub.resumetemplate'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
