# Generated by Django 5.2.5 on 2026-06-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0025_remove_resumeproject_last_generated_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioproject',
            name='theme_key',
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='portfolio_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_projects', to='portfoliohub.portfoliotheme'),
        ),
        migrations.AddField(
            model_name='portfoliotheme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliotheme',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
