# Generated by Django 5.2.5 on 2026-06-22 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0026_remove_portfolioproject_theme_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplateSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resumetemplatesection_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('section_key', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portfoliohub.resumetemplate')),
            ],
        ),
    ]
