# Generated by Django 5.2.5 on 2026-06-23 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0027_resumetemplatesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mastersection_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='resumetemplatesection',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='resumetemplatesection',
            name='section_key',
        ),
        migrations.AddField(
            model_name='resumetemplatesection',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_sections', to='portfoliohub.mastersection'),
        ),
        migrations.AddConstraint(
            model_name='resumetemplatesection',
            constraint=models.UniqueConstraint(fields=('template', 'section'), name='unique_template_section'),
        ),
    ]
