# Generated by Django 5.2.5 on 2026-06-23 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohub', '0028_mastersection_alter_resumetemplatesection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioThemeSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('portfoliothemesection_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_theme_sections', to='portfoliohub.mastersection')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portfoliohub.portfoliotheme')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('theme', 'section')},
            },
        ),
    ]
