# Generated by Django 5.2.5 on 2026-01-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhub', '0002_spotcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelspot',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='travel_spots', to='travelhub.spotcategory'),
        ),
    ]
