# Generated by Django 5.2.5 on 2026-01-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhub', '0003_travelspot_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelspot',
            name='best_time_to_visit',
            field=models.CharField(blank=True, help_text='e.g. Oct–Mar, Early Morning, Evenings', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='entry_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entry fee in local currency; 0 for free', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
