# Generated by Django 5.2.5 on 2026-01-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('travelhub', '0004_travelspot_best_time_to_visit_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='travelspot',
            name='travelhub_t_city_950264_idx',
        ),
        migrations.RemoveField(
            model_name='travelspot',
            name='city',
        ),
        migrations.AddField(
            model_name='travelspot',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.country'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.district'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.pincode'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.state'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='sub_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.subdistrict'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.village'),
        ),
    ]
