# Generated by Django 5.2.5 on 2026-01-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhub', '0005_remove_travelspot_travelhub_t_city_950264_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelspot',
            name='completion_status',
            field=models.CharField(choices=[('basic_info', 'Basic Information'), ('location', 'Location Added'), ('details', 'Details Added'), ('images', 'Images Added'), ('complete', 'Complete')], db_index=True, default='basic_info', max_length=20),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='is_ready_for_review',
            field=models.BooleanField(default=False, help_text='Admin review required before public listing'),
        ),
        migrations.AlterField(
            model_name='travelspot',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
