# Generated by Django 5.2.5 on 2026-01-26 18:02

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhub', '0006_travelspot_completion_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spotimage_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('public_id', models.CharField(editable=False, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spotimages_created', to=settings.AUTH_USER_MODEL)),
                ('travelspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travelhub.travelspot')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spotimages_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['spotimage_id'], name='travelhub_s_spotima_d11003_idx'), models.Index(fields=['is_primary'], name='travelhub_s_is_prim_21a006_idx')],
            },
        ),
    ]
