# Generated by Django 5.2.5 on 2026-02-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhub', '0007_spotimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelspot',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
