# Generated by Django 5.2.5 on 2026-02-06 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhub', '0008_travelspot_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelSpotView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('travelspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='travelhub.travelspot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['travelspot'], name='travelhub_t_travels_3a09a2_idx'), models.Index(fields=['viewed_at'], name='travelhub_t_viewed__cca009_idx')],
            },
        ),
    ]
