# Generated by Django 5.2.5 on 2026-03-24 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('travelhub', '0009_travelspotview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='travelspot',
            index=models.Index(fields=['state'], name='travelhub_t_state_i_465937_idx'),
        ),
        migrations.AddIndex(
            model_name='travelspot',
            index=models.Index(fields=['district'], name='travelhub_t_distric_f26dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='travelspot',
            index=models.Index(fields=['sub_district'], name='travelhub_t_sub_dis_358cca_idx'),
        ),
        migrations.AddIndex(
            model_name='travelspot',
            index=models.Index(fields=['village'], name='travelhub_t_village_a0c901_idx'),
        ),
        migrations.AddIndex(
            model_name='travelspot',
            index=models.Index(fields=['view_count'], name='travelhub_t_view_co_d1e9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='travelspot',
            index=models.Index(fields=['created_at'], name='travelhub_t_created_349564_idx'),
        ),
    ]
